### ISSUE TITLE
TypeError: Cannot read property 'MemoryStore' of undefined

### ISSUE THREAD

**Issue by grisuno** [junwatu/nodejs-express-mongo-login-reg-app#1]
show me this error on $ node server.js

```
at Object.<anonymous> (/var/lib/openshift/577a59302d5271497900012a/app-root/runtime/repo/server.js:18:45)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Module.runMain (module.js:575:10)
at run (node.js:348:7)
at startup (node.js:140:9)
at node.js:463:3
```

**Comment by edgartu** [comment]
the solution is 

MemoryStore = express.session.MemoryStore,
sessionStore = new MemoryStore();
write this way...
